# Generated by Django 2.1.2 on 2018-10-19 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crianca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crianca',
            name='prof_mae',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='prof_pai',
        ),
        migrations.AddField(
            model_name='crianca',
            name='possui_agua_encanada',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='crianca',
            name='profissao_mae',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='crianca',
            name='profissao_pai',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='escolaridade_mae',
            field=models.CharField(blank=True, choices=[('Primario Incompleto', 'Primário Incompleto'), ('Primario Completo', 'Primário Completo'), ('Ginasio Incompleto', 'Ginásio Incompleto'), ('Ginasio Completo', 'Ginásio Completo'), ('2 Grau Incompleto AcadEmico', '2º Grau Incompleto Acadêmico'), ('2 Grau Completo Academico', '2º Grau Completo Acadêmico'), ('2 Grau Incompleto Tecnico', '2º Grau Incompleto Técnico'), ('2 Grau Completo Tecnico', '2º Grau Completo Técnico'), ('3 Grau Incompleto', '3º Grau Incompleto'), ('3 Grau Completo', '3º Grau Completo'), ('Pos Graduacao ou Especializacao Cursando', 'Pós Grad./Espec. Cursando'), ('Pos Graduacao ou Especializacao Concluido', 'Pós Grad./Espec. Concluído'), ('Mestrado Cursando', 'Mestrado Cursando'), ('Mestrado Concluido', 'Mestrado Concluído'), ('Doutorado Cursando', 'Doutorado Cursando'), ('Doutorado Concluido', 'Doutorado Concluído'), ('MBA Cursando', 'MBA Cursando'), ('MBA ConcluIdo', 'MBA Concluído')], max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='escolaridade_pai',
            field=models.CharField(blank=True, choices=[('Primario Incompleto', 'Primário Incompleto'), ('Primario Completo', 'Primário Completo'), ('Ginasio Incompleto', 'Ginásio Incompleto'), ('Ginasio Completo', 'Ginásio Completo'), ('2 Grau Incompleto AcadEmico', '2º Grau Incompleto Acadêmico'), ('2 Grau Completo Academico', '2º Grau Completo Acadêmico'), ('2 Grau Incompleto Tecnico', '2º Grau Incompleto Técnico'), ('2 Grau Completo Tecnico', '2º Grau Completo Técnico'), ('3 Grau Incompleto', '3º Grau Incompleto'), ('3 Grau Completo', '3º Grau Completo'), ('Pos Graduacao ou Especializacao Cursando', 'Pós Grad./Espec. Cursando'), ('Pos Graduacao ou Especializacao Concluido', 'Pós Grad./Espec. Concluído'), ('Mestrado Cursando', 'Mestrado Cursando'), ('Mestrado Concluido', 'Mestrado Concluído'), ('Doutorado Cursando', 'Doutorado Cursando'), ('Doutorado Concluido', 'Doutorado Concluído'), ('MBA Cursando', 'MBA Cursando'), ('MBA ConcluIdo', 'MBA Concluído')], max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='nasceu_tempo_meses',
            field=models.PositiveIntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='nasceu_tempo_semanas',
            field=models.PositiveIntegerField(blank=True, default=40, null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='numero_pessoas_casa',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='peso_ao_nascer',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='renda_familia',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='visita_prenatal',
            field=models.CharField(choices=[('0', 'Nao fez/Nao Lembra'), ('1 a 3', 'De 1 a 3 visitas'), ('4 a 6', 'De 4 a 6 visitas'), ('7 a 9', 'De 7 a 9 visitas'), ('Mais de 9', 'Mais de 9 visitas')], max_length=100),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='zona',
            field=models.CharField(blank=True, choices=[('Zona Norte', 'Norte'), ('Zona Leste', 'Leste'), ('Zona Sul', 'Sul'), ('Zona Sudeste', 'Sudeste'), ('Centro', 'Centro')], max_length=12, null=True),
        ),
    ]
