# Generated by Django 2.0 on 2018-01-10 03:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crianca', '0002_auto_20180109_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='prof_mae',
            new_name='profissao_mae',
        ),
        migrations.RenameField(
            model_name='crianca',
            old_name='prof_pai',
            new_name='profissao_pai',
        ),
        migrations.AlterField(
            model_name='crianca',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2018, 1, 10, 3, 40, 55, 892588, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='nasceu_tempo_meses',
            field=models.PositiveIntegerField(blank=True, default=9),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='nasceu_tempo_semanas',
            field=models.PositiveIntegerField(blank=True, default=40),
        ),
    ]
