# Generated by Django 2.0 on 2018-01-10 03:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crianca', '0003_auto_20180110_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2018, 1, 10, 3, 49, 15, 781649, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='nome_mae',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='nome_pai',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
