# Generated by Django 2.0 on 2018-01-10 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crianca', '0004_auto_20180110_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
