# Generated by Django 2.0 on 2018-01-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crianca', '0006_auto_20180110_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='nasceu_tempo_meses',
            field=models.PositiveIntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='nasceu_tempo_semanas',
            field=models.PositiveIntegerField(blank=True, default=40, null=True),
        ),
    ]
