# Generated by Django 2.0 on 2018-01-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crianca', '0009_auto_20180111_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='renda_familia',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
