# Generated by Django 2.0 on 2019-10-09 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, null=True, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, null=True, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=12, null=True, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil')),
                ('telefone', models.CharField(max_length=12, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('pode_validar', 'Pode validar'), ('can_delete', 'Can Delete')),
            },
        ),
    ]
