# Generated by Django 2.1.2 on 2018-10-19 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'permissions': (('pode_validar', 'Pode validar'), ('can_delete', 'Can Delete'))},
        ),
        migrations.RemoveField(
            model_name='professor',
            name='genero',
        ),
        migrations.AddField(
            model_name='professor',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
        migrations.AddField(
            model_name='professor',
            name='sexo',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=12, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=30, null=True, verbose_name='Nome'),
        ),
    ]
