# Generated by Django 2.0 on 2018-01-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_auto_20180104_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='sexo',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=12, null=True, verbose_name='Sexo'),
        ),
    ]
