# Generated by Django 2.0 on 2018-01-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0005_auto_20180108_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
    ]
