# Generated by Django 2.0 on 2018-01-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0006_professor_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome'),
        ),
    ]
