# Generated by Django 2.0 on 2018-01-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0007_auto_20180110_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=40, null=True, verbose_name='Nome'),
        ),
    ]
