# Generated by Django 2.0 on 2017-12-26 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, null=True, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, null=True, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[(0, 'Feminino'), (1, 'Masculino')], max_length=1, null=True, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('matricula', models.CharField(max_length=11, null=True, verbose_name='Matrícula')),
                ('telefone', models.CharField(max_length=12, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
