# Generated by Django 2.0 on 2018-01-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_auto_20180106_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
    ]
