# Generated by Django 2.0 on 2018-01-11 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca_na_gravidez', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('qual_doenca', models.CharField(blank=True, max_length=30, null=True)),
                ('limpa_boca_bebe', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('quem_limpa_boca', models.CharField(blank=True, choices=[('Mae', 'Mãe'), ('Pai', 'Pai'), ('Avos', 'Avós'), ('Outro Parente', 'Outro parente'), ('Baba', 'Babá'), ('Outra pessoa', 'Outra pessoa')], max_length=10, null=True)),
                ('com_que_limpa', models.CharField(blank=True, max_length=20, null=True)),
                ('quando_comecou', models.CharField(blank=True, max_length=20, null=True)),
                ('quem_orientou', models.CharField(blank=True, max_length=20, null=True)),
                ('horarios', models.CharField(blank=True, max_length=20, null=True)),
                ('aceita_limpar', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('quando_nao_aceita', models.CharField(blank=True, choices=[('Dessite', 'Desiste'), ('Insiste', 'Insiste')], max_length=8, null=True)),
                ('tempo_amamentacao', models.PositiveIntegerField(default=0, null=True)),
                ('ainda_mama', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('quando_parou_mamar', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('idade_peito_noite', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('usou_mamadeira', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('iniciou_mamadeira', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('deixou_mamadeira', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('idade_usou_durante_sono', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('conteudo_mamadeira', models.CharField(blank=True, max_length=30, null=True)),
                ('historico_alergias', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('qual_alergia', models.CharField(blank=True, max_length=30, null=True)),
                ('relato_problema_saude', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('qual_problema_saude', models.CharField(blank=True, max_length=30, null=True)),
                ('historico_desordens_sanguineas', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('qual_desordem_sanguinea', models.CharField(blank=True, max_length=30, null=True)),
                ('tomando_algum_medicamento', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('qual_medicamento', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='anamnese')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
