# Generated by Django 2.0 on 2018-01-12 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crianca', '0010_auto_20180111_0125'),
        ('exame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeiraConsultaComDentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amamentacao_noturna', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('mama', models.CharField(blank=True, choices=[('Peito', 'Peito'), ('Mamadeira', 'Mamadeira')], max_length=10, null=True)),
                ('conteudo_mamadeira', models.CharField(blank=True, max_length=20, null=True)),
                ('ingere_guloseimas', models.CharField(blank=True, choices=[('3x por Semana', 'Até 3x por Semana'), ('Raramente', 'Raramente'), ('Livremente', 'Livremente'), ('Nunca', 'Nunca')], max_length=12, null=True)),
                ('hb_ao_dia', models.CharField(choices=[('2 vezes ao dia', '2 vezes ao dia'), ('1 vez ao dia', '1 vez ao dia'), ('Mais de 4 vezes ao dia', 'Mais de 4 vezes ao dia'), ('3 vezes ao dia', '3 vezes ao dia'), ('4 vezes ao dia', '4 vezes ao dia')], max_length=20, null=True)),
                ('horarios_hb', models.CharField(max_length=20, null=True)),
                ('quem_faz_hb', models.CharField(choices=[('Mae', 'Mãe'), ('Pai', 'Pai'), ('Avos', 'Avós'), ('Outro Parente', 'Outro parente'), ('Baba', 'Babá'), ('Outra pessoa', 'Outra pessoa')], max_length=20, null=True)),
                ('aceita_higienizar', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('quando_nao_aceita', models.CharField(blank=True, choices=[('Dessite', 'Desiste'), ('Insiste', 'Insiste')], max_length=12, null=True)),
                ('relato_problema_saude', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('qual_problema_saude', models.CharField(blank=True, max_length=20, null=True)),
                ('habitos_nao_nutritivos', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('quais_habitos', models.CharField(blank=True, max_length=20, null=True)),
                ('frequencia_habitos', models.CharField(blank=True, max_length=20, null=True)),
                ('quando_comecou_habitos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('permanece_habito', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('idade_permanceu_habitos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('problemas_habitos', models.CharField(blank=True, max_length=20, null=True)),
                ('irrompeu_dente', models.CharField(choices=[('Nao lembra', 'Nao lembra'), ('Nasceu com dente', 'Nasceu com dente'), ('Informar Idade', 'Informar Idade')], max_length=12, null=True)),
                ('idade_primeiro_dente', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('problema_dentes_irromperam', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('quais_problemas', models.CharField(blank=True, max_length=20, null=True)),
                ('diario_alimentar', models.CharField(max_length=20, null=True)),
                ('caries_mae', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('caries_pai', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('caries_irmaos', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('classificacao_boca_mae', models.CharField(choices=[('Mae nao presente', 'Mae nao esta presente'), ('Regular', 'Regular'), ('Ruim', 'Ruim'), ('Boa', 'Boa')], max_length=16, null=True)),
                ('sofreu_traumatismos', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('trauma', models.CharField(blank=True, max_length=20, null=True)),
                ('lesou_tecido', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('procurou_dentista', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('procurou_dentista_tempo', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('data_cadastro', models.DateField(null=True)),
                ('crianca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crianca.Crianca')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='anamnese',
            name='crianca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crianca.Crianca'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='data_cadastro',
            field=models.DateField(null=True),
        ),
    ]
