# Generated by Django 2.0 on 2018-01-12 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crianca', '0010_auto_20180111_0125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exame', '0002_auto_20180111_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeiraConsultaSemDentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitos_nao_nutritivos', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('quais_habitos', models.CharField(blank=True, max_length=20, null=True)),
                ('frequencia_habitos', models.CharField(blank=True, max_length=20, null=True)),
                ('quando_comecou_habitos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('permanece_habito', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('idade_permanceu_habitos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('problemas_habitos', models.CharField(blank=True, max_length=20, null=True)),
                ('caries_mae', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('caries_pai', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('caries_irmaos', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('classificacao_boca_mae', models.CharField(choices=[('Mae nao presente', 'Mae nao esta presente'), ('Regular', 'Regular'), ('Boa', 'Boa'), ('Ruim', 'Ruim')], max_length=16, null=True)),
                ('motivo_caries', models.CharField(max_length=20, null=True)),
                ('como_prevenir', models.CharField(max_length=20, null=True)),
                ('examina_boca', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('data_cadastro', models.DateField(null=True)),
                ('crianca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crianca.Crianca')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='primeiraconsultacomdentes',
            name='motivo_caries',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='quando_nao_aceita',
            field=models.CharField(blank=True, choices=[('Insiste', 'Insiste'), ('Dessite', 'Desiste')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Mae nao presente', 'Mae nao esta presente'), ('Regular', 'Regular'), ('Boa', 'Boa'), ('Ruim', 'Ruim')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='hb_ao_dia',
            field=models.CharField(choices=[('2 vezes ao dia', '2 vezes ao dia'), ('1 vez ao dia', '1 vez ao dia'), ('4 vezes ao dia', '4 vezes ao dia'), ('Mais de 4 vezes ao dia', 'Mais de 4 vezes ao dia'), ('3 vezes ao dia', '3 vezes ao dia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='ingere_guloseimas',
            field=models.CharField(blank=True, choices=[('3x por Semana', 'Até 3x por Semana'), ('Nunca', 'Nunca'), ('Livremente', 'Livremente'), ('Raramente', 'Raramente')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='irrompeu_dente',
            field=models.CharField(choices=[('Informar Idade', 'Informar Idade'), ('Nao lembra', 'Nao lembra'), ('Nasceu com dente', 'Nasceu com dente')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='mama',
            field=models.CharField(blank=True, choices=[('Mamadeira', 'Mamadeira'), ('Peito', 'Peito')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='quando_nao_aceita',
            field=models.CharField(blank=True, choices=[('Insiste', 'Insiste'), ('Dessite', 'Desiste')], max_length=12, null=True),
        ),
    ]
