# Generated by Django 2.0 on 2018-01-12 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crianca', '0010_auto_20180111_0125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exame', '0003_auto_20180111_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameClinicoSemDentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua_suja', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('tecido_mole', models.CharField(choices=[('Alterado', 'Alterado'), ('Normal', 'Normal')], max_length=12, null=True)),
                ('tecido_alterado', models.CharField(blank=True, max_length=20, null=True)),
                ('lingua', models.CharField(choices=[('Normal', 'Normal'), ('Geografica', 'Geográfica'), ('Sulcada', 'Sulcada'), ('Outro', 'Outro')], max_length=12, null=True)),
                ('tipo_lingua', models.CharField(blank=True, max_length=20, null=True)),
                ('anquiloglossia', models.CharField(choices=[('Nao permitiu Avaliar', 'Não permitiu Avaliar'), ('Sim', 'Sim'), ('Inconclusivo', 'Inconclusivo'), ('Nao', 'Não')], max_length=12, null=True)),
                ('data_cadastro', models.DateField(null=True)),
                ('crianca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crianca.Crianca')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Mae nao presente', 'Mae nao esta presente'), ('Ruim', 'Ruim'), ('Boa', 'Boa')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='hb_ao_dia',
            field=models.CharField(choices=[('1 vez ao dia', '1 vez ao dia'), ('Mais de 4 vezes ao dia', 'Mais de 4 vezes ao dia'), ('2 vezes ao dia', '2 vezes ao dia'), ('4 vezes ao dia', '4 vezes ao dia'), ('3 vezes ao dia', '3 vezes ao dia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='ingere_guloseimas',
            field=models.CharField(blank=True, choices=[('3x por Semana', 'Até 3x por Semana'), ('Livremente', 'Livremente'), ('Nunca', 'Nunca'), ('Raramente', 'Raramente')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='irrompeu_dente',
            field=models.CharField(choices=[('Nasceu com dente', 'Nasceu com dente'), ('Informar Idade', 'Informar Idade'), ('Nao lembra', 'Nao lembra')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='mama',
            field=models.CharField(blank=True, choices=[('Peito', 'Peito'), ('Mamadeira', 'Mamadeira')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultasemdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Mae nao presente', 'Mae nao esta presente'), ('Ruim', 'Ruim'), ('Boa', 'Boa')], max_length=16, null=True),
        ),
    ]
