# Generated by Django 2.0 on 2018-01-12 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crianca', '0010_auto_20180111_0125'),
        ('exame', '0004_auto_20180111_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameClinicoComDentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('lingua_suja', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('sangramento_escovacao', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('tecidos_moles', models.CharField(choices=[('Alterado', 'Alterado'), ('Normal', 'Normal')], max_length=20)),
                ('tecidos_moles_alteracao', models.CharField(blank=True, max_length=100)),
                ('lingua', models.CharField(choices=[('Geografica', 'Geográfica'), ('Normal', 'Normal'), ('Outro', 'Outro'), ('Sulcada', 'Sulcada')], max_length=15)),
                ('lingua_tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('anquiloglossia', models.CharField(choices=[('Nao', 'Não'), ('Nao permitiu Avaliar', 'Não permitiu Avaliar'), ('Inconclusivo', 'Inconclusivo'), ('Sim', 'Sim')], max_length=30)),
                ('denticao_completa', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=4)),
                ('arco_superior', models.CharField(blank=True, choices=[('Tipo I', 'Tipo I'), ('Tipo II', 'Tipo II')], max_length=30)),
                ('arco_inferior', models.CharField(blank=True, choices=[('Tipo I', 'Tipo I'), ('Tipo II', 'Tipo II')], max_length=30)),
                ('diastema_primata_superior', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=4)),
                ('diastema_primata_inferior', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=4)),
                ('mordida_cruzada_posterior', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=4)),
                ('mordida_cruzada_anterior', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=4)),
                ('mordida_aberta_anterior', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=4)),
                ('relacao_canina_direita', models.CharField(blank=True, choices=[('Classe I', 'Classe I'), ('Classe II', 'Classe II'), ('Classe III', 'Classe III')], max_length=15)),
                ('relacao_canina_esquerda', models.CharField(blank=True, choices=[('Classe I', 'Classe I'), ('Classe II', 'Classe II'), ('Classe III', 'Classe III')], max_length=15)),
                ('dente_55', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_54', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_53', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_52', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_51', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_65', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_64', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_63', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_62', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_61', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_85', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_84', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_83', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_82', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_81', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_75', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_74', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_73', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_72', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('dente_71', models.CharField(blank=True, choices=[('F', 'F'), ('T', 'T'), ('DEE', 'DEE'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('G', 'G'), ('S', 'S'), ('R', 'R')], max_length=5, null=True)),
                ('consulta', models.BooleanField(default=False)),
                ('atividade_educativa', models.BooleanField(default=False)),
                ('aplicacao_fluor', models.BooleanField(default=False)),
                ('art', models.BooleanField(default=False)),
                ('art_opcao', models.CharField(blank=True, max_length=20, null=True)),
                ('frenotomia', models.BooleanField(default=False)),
                ('enc_tratamento_odonto', models.BooleanField(default=False)),
                ('enc_UFPI_idade', models.BooleanField(default=False)),
                ('observacoes', models.CharField(blank=True, max_length=100)),
                ('planejamento', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ExameComDentes')),
                ('data_cadastro', models.DateField(null=True)),
                ('crianca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crianca.Crianca')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='quando_nao_aceita',
            field=models.CharField(blank=True, choices=[('Dessite', 'Desiste'), ('Insiste', 'Insiste')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='anquiloglossia',
            field=models.CharField(choices=[('Nao', 'Não'), ('Nao permitiu Avaliar', 'Não permitiu Avaliar'), ('Inconclusivo', 'Inconclusivo'), ('Sim', 'Sim')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='lingua',
            field=models.CharField(choices=[('Geografica', 'Geográfica'), ('Normal', 'Normal'), ('Outro', 'Outro'), ('Sulcada', 'Sulcada')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Boa', 'Boa'), ('Mae nao presente', 'Mae nao esta presente'), ('Ruim', 'Ruim')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='hb_ao_dia',
            field=models.CharField(choices=[('1 vez ao dia', '1 vez ao dia'), ('4 vezes ao dia', '4 vezes ao dia'), ('2 vezes ao dia', '2 vezes ao dia'), ('Mais de 4 vezes ao dia', 'Mais de 4 vezes ao dia'), ('3 vezes ao dia', '3 vezes ao dia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='ingere_guloseimas',
            field=models.CharField(blank=True, choices=[('Livremente', 'Livremente'), ('Raramente', 'Raramente'), ('Nunca', 'Nunca'), ('3x por Semana', 'Até 3x por Semana')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='quando_nao_aceita',
            field=models.CharField(blank=True, choices=[('Dessite', 'Desiste'), ('Insiste', 'Insiste')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultasemdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Boa', 'Boa'), ('Mae nao presente', 'Mae nao esta presente'), ('Ruim', 'Ruim')], max_length=16, null=True),
        ),
    ]
