# Generated by Django 2.0 on 2018-01-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0005_auto_20180111_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exameclinicocomdentes',
            old_name='foto',
            new_name='imagem',
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='quando_nao_aceita',
            field=models.CharField(blank=True, choices=[('Insiste', 'Insiste'), ('Dessite', 'Desiste')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='anquiloglossia',
            field=models.CharField(choices=[('Nao permitiu Avaliar', 'Não permitiu Avaliar'), ('Inconclusivo', 'Inconclusivo'), ('Nao', 'Não'), ('Sim', 'Sim')], max_length=30),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_51',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_52',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_53',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_54',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_55',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_61',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_62',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_63',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_64',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_65',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_71',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_72',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_73',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_74',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_75',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_81',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_82',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_83',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_84',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_85',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('T', 'T'), ('R', 'R'), ('A', 'A'), ('F', 'F'), ('S', 'S'), ('DEE', 'DEE'), ('MB', 'MB'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='lingua',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Geografica', 'Geográfica'), ('Sulcada', 'Sulcada'), ('Outro', 'Outro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='tecidos_moles',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='anquiloglossia',
            field=models.CharField(choices=[('Nao permitiu Avaliar', 'Não permitiu Avaliar'), ('Inconclusivo', 'Inconclusivo'), ('Nao', 'Não'), ('Sim', 'Sim')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='lingua',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Geografica', 'Geográfica'), ('Sulcada', 'Sulcada'), ('Outro', 'Outro')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='tecido_mole',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Boa', 'Boa'), ('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Mae nao presente', 'Mae nao esta presente')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='hb_ao_dia',
            field=models.CharField(choices=[('2 vezes ao dia', '2 vezes ao dia'), ('3 vezes ao dia', '3 vezes ao dia'), ('Mais de 4 vezes ao dia', 'Mais de 4 vezes ao dia'), ('4 vezes ao dia', '4 vezes ao dia'), ('1 vez ao dia', '1 vez ao dia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='ingere_guloseimas',
            field=models.CharField(blank=True, choices=[('Raramente', 'Raramente'), ('Nunca', 'Nunca'), ('3x por Semana', 'Até 3x por Semana'), ('Livremente', 'Livremente')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='irrompeu_dente',
            field=models.CharField(choices=[('Nao lembra', 'Nao lembra'), ('Informar Idade', 'Informar Idade'), ('Nasceu com dente', 'Nasceu com dente')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='quando_nao_aceita',
            field=models.CharField(blank=True, choices=[('Insiste', 'Insiste'), ('Dessite', 'Desiste')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultasemdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Boa', 'Boa'), ('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Mae nao presente', 'Mae nao esta presente')], max_length=16, null=True),
        ),
    ]
