# Generated by Django 2.0 on 2018-01-16 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0006_auto_20180111_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='crianca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crianca.Crianca'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='quando_nao_aceita',
            field=models.CharField(blank=True, choices=[('Dessite', 'Desiste'), ('Insiste', 'Insiste')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='anquiloglossia',
            field=models.CharField(choices=[('Nao', 'Não'), ('Sim', 'Sim'), ('Nao permitiu Avaliar', 'Não permitiu Avaliar'), ('Inconclusivo', 'Inconclusivo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_51',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_52',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_53',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_54',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_55',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_61',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_62',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_63',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_64',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_65',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_71',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_72',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_73',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_74',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_75',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_81',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_82',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_83',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_84',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_85',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('MB', 'MB'), ('A', 'A'), ('C', 'C'), ('F', 'F'), ('DEE', 'DEE'), ('G', 'G')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='lingua',
            field=models.CharField(choices=[('Geografica', 'Geográfica'), ('Normal', 'Normal'), ('Outro', 'Outro'), ('Sulcada', 'Sulcada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='anquiloglossia',
            field=models.CharField(choices=[('Nao', 'Não'), ('Sim', 'Sim'), ('Nao permitiu Avaliar', 'Não permitiu Avaliar'), ('Inconclusivo', 'Inconclusivo')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='lingua',
            field=models.CharField(choices=[('Geografica', 'Geográfica'), ('Normal', 'Normal'), ('Outro', 'Outro'), ('Sulcada', 'Sulcada')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Ruim', 'Ruim'), ('Mae nao presente', 'Mae nao esta presente'), ('Boa', 'Boa'), ('Regular', 'Regular')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='hb_ao_dia',
            field=models.CharField(choices=[('3 vezes ao dia', '3 vezes ao dia'), ('Mais de 4 vezes ao dia', 'Mais de 4 vezes ao dia'), ('2 vezes ao dia', '2 vezes ao dia'), ('1 vez ao dia', '1 vez ao dia'), ('4 vezes ao dia', '4 vezes ao dia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='ingere_guloseimas',
            field=models.CharField(blank=True, choices=[('3x por Semana', 'Até 3x por Semana'), ('Raramente', 'Raramente'), ('Livremente', 'Livremente'), ('Nunca', 'Nunca')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='quando_nao_aceita',
            field=models.CharField(blank=True, choices=[('Dessite', 'Desiste'), ('Insiste', 'Insiste')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultasemdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Ruim', 'Ruim'), ('Mae nao presente', 'Mae nao esta presente'), ('Boa', 'Boa'), ('Regular', 'Regular')], max_length=16, null=True),
        ),
    ]
