# Generated by Django 2.0 on 2018-01-16 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0008_auto_20180116_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='anquiloglossia',
            field=models.CharField(choices=[('Nao permitiu Avaliar', 'Não permitiu Avaliar'), ('Inconclusivo', 'Inconclusivo'), ('Nao', 'Não'), ('Sim', 'Sim')], max_length=30),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='crianca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crianca.Crianca'),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_51',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_52',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_53',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_54',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_55',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_61',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_62',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_63',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_64',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_65',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_71',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_72',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_73',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_74',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_75',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_81',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_82',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_83',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_84',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_85',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('R', 'R'), ('F', 'F'), ('DEE', 'DEE'), ('T', 'T'), ('C', 'C'), ('A', 'A'), ('MB', 'MB'), ('S', 'S')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='lingua',
            field=models.CharField(choices=[('Outro', 'Outro'), ('Sulcada', 'Sulcada'), ('Geografica', 'Geográfica'), ('Normal', 'Normal')], max_length=15),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='anquiloglossia',
            field=models.CharField(choices=[('Nao permitiu Avaliar', 'Não permitiu Avaliar'), ('Inconclusivo', 'Inconclusivo'), ('Nao', 'Não'), ('Sim', 'Sim')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='crianca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crianca.Crianca'),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='lingua',
            field=models.CharField(choices=[('Outro', 'Outro'), ('Sulcada', 'Sulcada'), ('Geografica', 'Geográfica'), ('Normal', 'Normal')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Mae nao presente', 'Mae nao esta presente'), ('Regular', 'Regular'), ('Ruim', 'Ruim'), ('Boa', 'Boa')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='crianca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crianca.Crianca'),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='hb_ao_dia',
            field=models.CharField(choices=[('4 vezes ao dia', '4 vezes ao dia'), ('1 vez ao dia', '1 vez ao dia'), ('2 vezes ao dia', '2 vezes ao dia'), ('Mais de 4 vezes ao dia', 'Mais de 4 vezes ao dia'), ('3 vezes ao dia', '3 vezes ao dia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='ingere_guloseimas',
            field=models.CharField(blank=True, choices=[('3x por Semana', 'Até 3x por Semana'), ('Livremente', 'Livremente'), ('Raramente', 'Raramente'), ('Nunca', 'Nunca')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='irrompeu_dente',
            field=models.CharField(choices=[('Nao lembra', 'Nao lembra'), ('Informar Idade', 'Informar Idade'), ('Nasceu com dente', 'Nasceu com dente')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='mama',
            field=models.CharField(blank=True, choices=[('Peito', 'Peito'), ('Mamadeira', 'Mamadeira')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultasemdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Mae nao presente', 'Mae nao esta presente'), ('Regular', 'Regular'), ('Ruim', 'Ruim'), ('Boa', 'Boa')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultasemdentes',
            name='crianca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crianca.Crianca'),
        ),
    ]
