# Generated by Django 2.0 on 2018-01-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0010_auto_20180117_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='quando_nao_aceita',
            field=models.CharField(blank=True, choices=[('Dessite', 'Desiste'), ('Insiste', 'Insiste')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='anquiloglossia',
            field=models.CharField(choices=[('Nao', 'Não'), ('Nao permitiu Avaliar', 'Não permitiu Avaliar'), ('Sim', 'Sim'), ('Inconclusivo', 'Inconclusivo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_51',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_52',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_53',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_54',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_55',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_61',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_62',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_63',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_64',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_65',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_71',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_72',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_73',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_74',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_75',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_81',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_82',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_83',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_84',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_85',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('A', 'A'), ('B', 'B'), ('K', 'K'), ('F', 'F'), ('G', 'G'), ('E', 'E'), ('C', 'C'), ('D', 'D'), ('T', 'T')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='tecidos_moles',
            field=models.CharField(choices=[('Alterado', 'Alterado'), ('Normal', 'Normal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='anquiloglossia',
            field=models.CharField(choices=[('Nao', 'Não'), ('Nao permitiu Avaliar', 'Não permitiu Avaliar'), ('Sim', 'Sim'), ('Inconclusivo', 'Inconclusivo')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='tecido_mole',
            field=models.CharField(choices=[('Alterado', 'Alterado'), ('Normal', 'Normal')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Mae nao presente', 'Mae nao esta presente'), ('Regular', 'Regular'), ('Boa', 'Boa'), ('Ruim', 'Ruim')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='hb_ao_dia',
            field=models.CharField(choices=[('Três vezes ao dia', 'Três vezes ao dia'), ('Quatro vezes ao dia', 'Quatro vezes ao dia'), ('Duas vezes ao dia', 'Duas vezes ao dia'), ('Mais de quatro vezes ao dia', 'Mais de quatro vezes ao dia'), ('Uma vez ao dia', 'Uma vez ao dia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='ingere_guloseimas',
            field=models.CharField(blank=True, choices=[('Nunca', 'Nunca'), ('Raramente', 'Raramente'), ('Três vezes por Semana', 'Até três vezes por Semana'), ('Livremente', 'Livremente')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='quando_nao_aceita',
            field=models.CharField(blank=True, choices=[('Dessite', 'Desiste'), ('Insiste', 'Insiste')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultasemdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Mae nao presente', 'Mae nao esta presente'), ('Regular', 'Regular'), ('Boa', 'Boa'), ('Ruim', 'Ruim')], max_length=16, null=True),
        ),
    ]
