# Generated by Django 2.0 on 2018-01-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0011_auto_20180119_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnese',
            old_name='image',
            new_name='imagem',
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='quando_nao_aceita',
            field=models.CharField(blank=True, choices=[('Insiste', 'Insiste'), ('Dessite', 'Desiste')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='anquiloglossia',
            field=models.CharField(choices=[('Nao permitiu Avaliar', 'Não permitiu Avaliar'), ('Nao', 'Não'), ('Sim', 'Sim'), ('Inconclusivo', 'Inconclusivo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_51',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_52',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_53',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_54',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_55',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_61',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_62',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_63',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_64',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_65',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_71',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_72',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_73',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_74',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_75',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_81',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_82',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_83',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_84',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='dente_85',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('K', 'K'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('C', 'C')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='lingua',
            field=models.CharField(choices=[('Sulcada', 'Sulcada'), ('Geografica', 'Geográfica'), ('Normal', 'Normal'), ('Outro', 'Outro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='exameclinicocomdentes',
            name='tecidos_moles',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='anquiloglossia',
            field=models.CharField(choices=[('Nao permitiu Avaliar', 'Não permitiu Avaliar'), ('Nao', 'Não'), ('Sim', 'Sim'), ('Inconclusivo', 'Inconclusivo')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='lingua',
            field=models.CharField(choices=[('Sulcada', 'Sulcada'), ('Geografica', 'Geográfica'), ('Normal', 'Normal'), ('Outro', 'Outro')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='exameclinicosemdentes',
            name='tecido_mole',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Boa', 'Boa'), ('Regular', 'Regular'), ('Ruim', 'Ruim'), ('Mae nao presente', 'Mae nao esta presente')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='hb_ao_dia',
            field=models.CharField(choices=[('Quatro vezes ao dia', 'Quatro vezes ao dia'), ('Uma vez ao dia', 'Uma vez ao dia'), ('Três vezes ao dia', 'Três vezes ao dia'), ('Mais de quatro vezes ao dia', 'Mais de quatro vezes ao dia'), ('Duas vezes ao dia', 'Duas vezes ao dia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='ingere_guloseimas',
            field=models.CharField(blank=True, choices=[('Três vezes por Semana', 'Até três vezes por Semana'), ('Nunca', 'Nunca'), ('Raramente', 'Raramente'), ('Livremente', 'Livremente')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='mama',
            field=models.CharField(blank=True, choices=[('Peito', 'Peito'), ('Mamadeira', 'Mamadeira')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultacomdentes',
            name='quando_nao_aceita',
            field=models.CharField(blank=True, choices=[('Insiste', 'Insiste'), ('Dessite', 'Desiste')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='primeiraconsultasemdentes',
            name='classificacao_boca_mae',
            field=models.CharField(choices=[('Boa', 'Boa'), ('Regular', 'Regular'), ('Ruim', 'Ruim'), ('Mae nao presente', 'Mae nao esta presente')], max_length=16, null=True),
        ),
    ]
